CREATE TABLE DBIMGR.DBI_ALERT_GENERATION
(
  OBJECT_TYPE      VARCHAR2(100 BYTE)           NOT NULL,
  OBJECT_NAME      VARCHAR2(200 BYTE)           NOT NULL,
  ALERT_TIME       DATE                         DEFAULT sysdate               NOT NULL,
  ALERT_INTERVAL   NUMBER                       DEFAULT 24                    NOT NULL,
  ALERT_THRESHOLD  NUMBER                       DEFAULT 75                    NOT NULL
)
TABLESPACE DBIDAT01
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON DBIMGR.DBI_ALERT_GENERATION TO DBIMGR_SELECT_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON DBIMGR.DBI_ALERT_GENERATION TO DBIMGR_UPDATE_ROLE;

