CREATE TABLE DBIMGR.DBI_METRIC_OBJECTTYPE
(
  METRIC_OBJECT_TYPE   VARCHAR2(30 BYTE)        NOT NULL,
  METRIC_OBJECT_VALUE  NUMBER,
  METRIC_TYPE_DESC     VARCHAR2(1000 BYTE)      NOT NULL
)
TABLESPACE DBIDAT01
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DBIMGR.DBI_METRIC_OBJECTTYPE_PK ON DBIMGR.DBI_METRIC_OBJECTTYPE
(METRIC_OBJECT_VALUE)
LOGGING
TABLESPACE DBIDAT01
NOPARALLEL;


ALTER TABLE DBIMGR.DBI_METRIC_OBJECTTYPE ADD (
  CONSTRAINT DBI_METRIC_OBJECTTYPE_PK
 PRIMARY KEY
 (METRIC_OBJECT_VALUE)
    USING INDEX 
    TABLESPACE DBIDAT01);



GRANT SELECT ON DBIMGR.DBI_METRIC_OBJECTTYPE TO DBIMGR_SELECT_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON DBIMGR.DBI_METRIC_OBJECTTYPE TO DBIMGR_UPDATE_ROLE;