CREATE TABLE DBIMGR.DBI_METRIC
(
  METRIC_VAL              NUMBER,
  METRIC_OPERATOR         VARCHAR2(100 BYTE)    NOT NULL,
  METRIC_DESCRIPTION      VARCHAR2(1000 BYTE)   NOT NULL,
  METRIC_UNIT             VARCHAR2(100 BYTE)    NOT NULL,
  METRIC_OBJECT_TYPE_VAL  NUMBER                NOT NULL,
  METRIC_ID               NUMBER                NOT NULL
)
TABLESPACE DBIDAT01
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DBIMGR.DBIMGR_METRIC_PK ON DBIMGR.DBI_METRIC
(METRIC_VAL)
LOGGING
TABLESPACE DBIDAT01
NOPARALLEL;


ALTER TABLE DBIMGR.DBI_METRIC ADD (
  CONSTRAINT DBIMGR_METRIC_PK
 PRIMARY KEY
 (METRIC_VAL)
    USING INDEX 
    TABLESPACE DBIDAT01);

ALTER TABLE DBIMGR.DBI_METRIC ADD (
  CONSTRAINT DBI_METRIC_R01 
 FOREIGN KEY (METRIC_OBJECT_TYPE_VAL) 
 REFERENCES DBIMGR.DBI_METRIC_OBJECTTYPE (METRIC_OBJECT_VALUE));


GRANT SELECT ON DBIMGR.DBI_METRIC TO DBIMGR_SELECT_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON DBIMGR.DBI_METRIC TO DBIMGR_UPDATE_ROLE;

